#!/bin/sh

# verbose
set -x

aclocal -I m4
autoheader
autoconf
case `uname` in Darwin*) glibtoolize --automake -c ;;
  *) libtoolize --automake -c ;; esac
automake -a -c

if test `basename ${0}` = "bootstrap-and-dist" ; then
  ./configure
  make dist
fi



