#! /bin/bash

REAL_PATH=`readlink -f "${0}"`
PARAVER_HOME="$( cd "$( dirname "$REAL_PATH" )" && pwd )"
export PARAVER_HOME=${PARAVER_HOME%/bin}

#if [ -z "${PARAVER_HOME}" ] ; then
#  echo "Please set \$PARAVER_HOME to the wxparaver installation root directory"
#  exit 1

if [ -d "${PARAVER_HOME}/lib/paraver-kernel" ] ; then
  LIB_DIR=lib
elif [ -d "${PARAVER_HOME}/lib64/paraver-kernel" ] ; then
  LIB_DIR=lib64
else
  echo "paraver-kernel libraries not found in \$PARAVER_HOME/{lib,lib64}/paraver-kernel/"
  exit 1
fi

if ! [ -e "${PARAVER_HOME}/bin/wxparaver.bin" ] ; then
  echo "wxparaver binary not found in \$PARAVER_HOME/bin/"
  exit 1
fi

LD_LIBRARY_PATH="${PARAVER_HOME}/${LIB_DIR}/ptools_common_files/:${PARAVER_HOME}/${LIB_DIR}/paraver-kernel:${PARAVER_HOME}/${LIB_DIR}/wxparaver:$LD_LIBRARY_PATH" "${PARAVER_HOME}/bin/wxparaver.bin" "$@"
	
